<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="ktsu.AppDataStorage" Version="1.16.33" />
    <PackageVersion Include="ktsu.Extensions" Version="1.5.35" />
    <PackageVersion Include="NJsonSchema" Version="11.6.1" />
    <PackageVersion Include="Polyfill" Version="11.0.2" />
    <PackageVersion Include="Spectre.Console" Version="0.57.0" />
    <PackageVersion Include="Spectre.Console.Cli" Version="0.55.0" />
  </ItemGroup>
</Project>
