<Project>
  <Sdk Name="Microsoft.NET.Sdk" />
  <Sdk Name="ktsu.Sdk" />
  <Sdk Name="ktsu.Sdk.ConsoleApp" />

  <ItemGroup>
    <PackageReference Include="ktsu.AppDataStorage" />
    <PackageReference Include="ktsu.Extensions" />
    <PackageReference Include="NJsonSchema" />
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Spectre.Console.Cli" />
  </ItemGroup>

</Project>
