<?xml version="1.0" encoding="utf-8"?>







<Project Sdk="ktsu.Sdk.App/1.8.0">
  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="ktsu.AppDataStorage" Version="1.16.17" />
    <PackageReference Include="ktsu.Extensions" Version="1.5.14" />
    <PackageReference Include="NJsonSchema" Version="11.6.1" />
    <PackageReference Include="Spectre.Console" Version="0.55.2" />
    <PackageReference Include="Spectre.Console.Cli" Version="0.55.0" />
    <PackageReference Include="Spectre.Console.ImageSharp" Version="0.55.2" />
    <PackageReference Include="Spectre.Console.Json" Version="0.55.2" />
    <PackageReference Include="Spectre.Console.Testing" Version="0.55.2" />
  </ItemGroup>
</Project>
