<Project>
  <Sdk Name="Microsoft.NET.Sdk" />
  <Sdk Name="ktsu.Sdk" />
  <Sdk Name="ktsu.Sdk.ConsoleApp" />

  <ItemGroup>
    <PackageReference Include="CommandLineParser" />
    <PackageReference Include="ktsu.AppDataStorage" />
    <PackageReference Include="ktsu.Extensions" />
    <PackageReference Include="NJsonSchema" />
    <PackageReference Include="Polyfill" PrivateAssets="all" />
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Spectre.Console.Ansi" />
    <PackageReference Include="Spectre.Console.Cli" />
    <PackageReference Include="Spectre.Console.ImageSharp" />
    <PackageReference Include="Spectre.Console.Json" />
    <PackageReference Include="Spectre.Console.Testing" />
  </ItemGroup>
</Project>
